#!/usr/bin/python3
# Generated by: Cursor IDE using the models Composer 2.5, Sonnet 4.6, Codex 5.3
"""Check if the first line of a string matches conventional commit format.

Validates the header using the Conventional Commits 1.0.0 format and the rules
from the linux-system-roles, which extends
@commitlint/config-conventional by allowing sentence-case, start-case,
pascal-case, and upper-case subjects and the
``tests`` type:
https://www.conventionalcommits.org/en/v1.0.0/
"""

from __future__ import annotations

import argparse
import os
import re
import sys

# conventional-changelog-conventionalcommits parser preset
PR_TITLE_PATTERN = re.compile(r"^(\w+)(?:\(([\w_-]+)\))?!?: (.+)$")

COMMIT_TYPES = (
    "build",
    "chore",
    "ci",
    "docs",
    "feat",
    "fix",
    "perf",
    "refactor",
    "revert",
    "style",
    "test",
    "tests",
)

DEFAULT_HEADER_MAX_LENGTH = 100

PASCAL_CASE_WORD = re.compile(r"^[A-Z][a-z0-9]*(?:[A-Z][a-z][a-z0-9]*)+$")
QUOTED_TEXT = re.compile(r'`.*?`|".*?"|' + r"'.*?'")
# es-toolkit/lodash words() splitter (ASCII commit subjects)
CASE_WORDS_PATTERN = re.compile(r"[A-Z]?[a-z]+|[0-9]+|[A-Z]+(?![a-z])")
URL_PATTERN = re.compile(r"^https?://\S+$", re.IGNORECASE)

PR_TITLE_ERROR_MESSAGE = f"""
Expected format:
    type(scope)!: subject
where:
    type is one of [{', '.join(COMMIT_TYPES)}]
    (scope) is optional - used to categorize the PR
    subject is required and must not be empty
    the `!` is optional and indicates a breaking change

    See https://linux-system-roles.github.io/contribute.html "Write a good PR title and description" for more details.
"""


class PrTitleFileFormatError(ValueError):
    """Raised when a PR title file line is malformed."""


def header_max_length() -> int:
    """Return the maximum allowed header length from PR_TITLE_LINT_LENGTH."""
    raw = os.environ.get("PR_TITLE_LINT_LENGTH")
    if raw is None or raw == "":
        return DEFAULT_HEADER_MAX_LENGTH
    try:
        value = int(raw)
    except ValueError as exc:
        raise SystemExit("PR_TITLE_LINT_LENGTH must be a positive integer") from exc
    if value <= 0:
        raise SystemExit("PR_TITLE_LINT_LENGTH must be a positive integer")
    return value


def _strip_quotes(value: str) -> str:
    return QUOTED_TEXT.sub("", value).strip()


def _upper_first(value: str) -> str:
    if not value:
        return value
    return value[0].upper() + value[1:]


def _normalize_for_case(value: str) -> str:
    return value.replace("'", "").replace("\u2019", "")


def _words_for_case(value: str) -> list[str]:
    return CASE_WORDS_PATTERN.findall(_normalize_for_case(value).strip())


def _start_case(value: str) -> str:
    """Port of es-toolkit startCase()."""
    words = _words_for_case(value)
    if not words:
        return value
    parts: list[str] = []
    for word in words:
        if word == word.upper():
            parts.append(word)
        else:
            parts.append(word[0].upper() + word[1:].lower())
    return " ".join(parts)


def _start_case_is_forbidden(value: str) -> bool:
    """True when a start-case-shaped subject should be rejected."""
    for index, raw_word in enumerate(value.split()):
        word = raw_word.strip("()[]{}:;,./!?")
        if index == 0:
            continue
        if word.isalpha() and word.isupper():
            continue
        if word and word[0].isupper():
            return True
    return False


def _camel_case(value: str) -> str:
    if PASCAL_CASE_WORD.match(value):
        return value[0].lower() + value[1:]
    normalized = re.sub(r"[^\w\s-]", " ", value)
    parts = [part for part in re.split(r"[\s_-]+", normalized) if part]
    if not parts:
        return value
    head, *tail = parts
    return head.lower() + "".join(part[:1].upper() + part[1:].lower() for part in tail)


def _to_case(value: str, target: str) -> str:
    if target == "sentence-case":
        return _upper_first(value)
    if target == "start-case":
        return _start_case(value)
    if target == "pascal-case":
        return _upper_first(_camel_case(value))
    if target in ("upper-case", "uppercase"):
        return value.upper()
    if target in ("lower-case", "lowercase", "lowerCase"):
        return value.lower()
    raise ValueError(f"unsupported case target: {target}")


def _ensure_case(raw: str, target: str) -> bool:
    """Port of @commitlint/ensure case()."""
    value = _strip_quotes(raw)
    if not value or value[0].isdigit():
        return True
    if target == "start-case" and _start_case_is_forbidden(value):
        return True
    transformed = _to_case(value, target)
    if transformed != value:
        return False
    return True


def _parse_pr_title(pr_title: str) -> dict[str, str | None]:
    match = PR_TITLE_PATTERN.match(pr_title)
    if not match:
        return {
            "pr_title": pr_title,
            "type": None,
            "scope": None,
            "subject": None,
        }
    commit_type, scope, subject = match.groups()
    return {
        "pr_title": pr_title,
        "type": commit_type,
        "scope": scope,
        "subject": subject,
    }


def lint_pr_title(text: str) -> list[str]:
    """Return commitlint-style error messages for the first line of text."""
    if not text:
        pr_title = ""
    else:
        pr_title = text.splitlines()[0]

    errors: list[str] = []
    parsed = _parse_pr_title(pr_title)

    starts_with_whitespace = bool(pr_title) and len(pr_title) > len(pr_title.lstrip())
    ends_with_whitespace = bool(pr_title) and len(pr_title) > len(pr_title.rstrip())
    if starts_with_whitespace and ends_with_whitespace:
        errors.append("pr_title must not be surrounded by whitespace")
    elif starts_with_whitespace:
        errors.append("pr_title must not start with whitespace")
    elif ends_with_whitespace:
        errors.append("pr_title must not end with whitespace")

    max_length = header_max_length()
    if len(pr_title) > max_length:
        errors.append(
            "pr_title must not be longer than "
            f"{max_length} characters, current length is {len(pr_title)}"
        )

    commit_type = parsed["type"]
    subject = parsed["subject"]

    if not commit_type:
        errors.append("format error")
    elif commit_type not in COMMIT_TYPES:
        errors.append(f"type must be one of [{', '.join(COMMIT_TYPES)}]")
    elif not _ensure_case(commit_type, "lower-case"):
        errors.append("type must be lower-case")

    if commit_type and (subject is None or subject == ""):
        errors.append("subject must not be empty")

    return errors


def parse_pr_title_file_line(
    line: str, *, line_number: int | None = None
) -> tuple[str, str] | None:
    """Return URL and title from one input line, or None for blank lines."""
    stripped = line.rstrip("\n\r")
    if not stripped.strip():
        return None
    if "\t" in stripped:
        url, title = stripped.split("\t", 1)
    else:
        parts = stripped.split(None, 1)
        if len(parts) != 2:
            location = f"line {line_number}: " if line_number is not None else ""
            raise PrTitleFileFormatError(
                f"{location}expected URL followed by PR title, got: {stripped!r}"
            )
        url, title = parts
    url = url.strip()
    title = title.strip()
    if not URL_PATTERN.match(url) or not title:
        location = f"line {line_number}: " if line_number is not None else ""
        raise PrTitleFileFormatError(
            f"{location}expected URL followed by PR title, got: {stripped!r}"
        )
    return url, title


def lint_pr_title_file(path: str) -> list[tuple[str, str]]:
    """Return (url, error) pairs for each invalid PR title in a file."""
    results: list[tuple[str, str]] = []
    file_handle = sys.stdin if path == "-" else open(path, encoding="utf-8")
    try:
        for line_number, line in enumerate(file_handle, start=1):
            parsed = parse_pr_title_file_line(line, line_number=line_number)
            if parsed is None:
                continue
            url, title = parsed
            for error in lint_pr_title(title):
                results.append((url, error))
    finally:
        if path != "-":
            file_handle.close()
    return results


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Check whether the first line of a string matches the conventional "
            "commit format used by linux-system-roles."
        )
    )
    parser.add_argument(
        "title",
        nargs="?",
        help="PR title or commit message to check (reads stdin if omitted)",
    )
    parser.add_argument(
        "-f",
        "--file",
        metavar="FILE",
        help=(
            "File with PR URL in the first column and PR title in the "
            "remaining columns; use - to read from stdin"
        ),
    )
    parser.add_argument(
        "-q",
        "--quiet",
        action="store_true",
        help="Only print a summary line and exit with a status code",
    )
    args = parser.parse_args(argv)

    if args.file is not None:
        if args.title is not None:
            parser.error("cannot use both -f and title argument")
        file_errors = lint_pr_title_file(args.file)
        if not args.quiet:
            for url, error in file_errors:
                print(f"{url}\t{error}")
            if file_errors:
                print(PR_TITLE_ERROR_MESSAGE)
        return 1 if file_errors else 0

    if args.title is not None:
        text = args.title
    elif not sys.stdin.isatty():
        text = sys.stdin.read()
    else:
        parser.error("title argument, -f FILE, or stdin input is required")

    errors = lint_pr_title(text)
    pr_title = text.splitlines()[0] if text else ""

    if errors:
        if not args.quiet:
            print(f"⧗   input: [{pr_title}]")
            for error in errors:
                print(f"✖   {error}")
            print(f"✖   found {len(errors)} problems, 0 warnings")
            print(PR_TITLE_ERROR_MESSAGE)
        return 1

    if not args.quiet:
        print(f"⧗   input: [{pr_title}]")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except PrTitleFileFormatError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(2)
