---
# input is
# * update_issue_key - key of issue to update e.g. "RHEL-001"
# fields to update
- name: Update fields
  community.general.jira:
    operation: edit
    issue: "{{ update_issue_key }}"
  when: __fields | length > 0
  args:
    fields: "{{ __fields }}"
  vars:
    # the key is the name of the variable used in the playbooks
    # the fieldname is the field used in jira corresponding to the variable
    # updatetype is how to pass the update - see the __fields code below
    __field_map:
      product:
        fieldname: customfield_12319040
        updatetype: list_of_value_dict
      itr:
        fieldname: fixVersions
        updatetype: list_of_name_dict
      itm:
        fieldname: customfield_12321040
        updatetype: value_dict
      dtm:
        fieldname: customfield_12318141
        updatetype: value_dict
      doc_text:
        fieldname: customfield_12317313
        updatetype: string
      doc_text_type:
        fieldname: customfield_12320850
        updatetype: value_dict
      pool_team:
        fieldname: customfield_12317259
        updatetype: list_of_value_dict
    __roles_list: "{{ [] if labels | d([]) | length > 0
      else roles | d('') | split(',') | sort }}"
    __labels: "{{ labels if labels | d([]) | length > 0
        else ['system_role_'] | product(__roles_list) | map('join')
        if roles | d('') else [] }}"
    __field_names: "{{ __field_map.keys() | sort }}"
    __fields_defined: "{{ q('varnames', *__field_names) }}"
    __fields: |
      {% set rv = {} %}
      {% for var in __fields_defined %}
      {%   set val = lookup("vars", var) %}
      {%   if __field_map[var]["updatetype"] == "string" %}
      {%     set item = val %}
      {%     set _ = rv.update({__field_map[var]["fieldname"]: item})%}
      {%   elif __field_map[var]["updatetype"] == "value_dict" %}
      {%     set item = {"value": val} %}
      {%     set _ = rv.update({__field_map[var]["fieldname"]: item})%}
      {%   elif __field_map[var]["updatetype"] == "list_of_name_dict" %}
      {%     set item = [{"name": val}] %}
      {%     set _ = rv.update({__field_map[var]["fieldname"]: item})%}
      {%   elif __field_map[var]["updatetype"] == "list_of_value_dict" %}
      {%     set item = [{"value": val}] %}
      {%     set _ = rv.update({__field_map[var]["fieldname"]: item})%}
      {%   elif __field_map[var]["updatetype"] == "list" %}
      {%     set item = [val] %}
      {%     set _ = rv.update({__field_map[var]["fieldname"]: item})%}
      {%   endif %}
      {% endfor %}
      {% if __labels %}
      {%   set _ = rv.update({"labels": __labels}) %}
      {% endif %}
      {{ rv }}

- name: Add comment
  community.general.jira:
    operation: comment
    issue: "{{ update_issue_key }}"
    comment: "{{ comment }}"
  when: comment | d('') | length > 0
