name: Publish fedora.linux_system_roles collection to Ansible Galaxy

on:
  workflow_dispatch:

jobs:
  publish_collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout auto-maintenance repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        shell: bash
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt install pandoc
          pip install --upgrade pip
          pip install --upgrade ansible-core galaxy-importer pypandoc rst2html 'zipp>=3.1.0' 'pyyaml<6,>=5.4.1'
          docker --version

      - name: Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access_token: ${{ secrets.GH_PUSH_TOKEN }}
          branch: ${{ github.event.repository.default_branch }}

      - name: Build and publish the collection
        shell: bash
        run: |
          set -euxo pipefail
          # Ensure there is no dest_path before running release_collection.py
          dest_path=/var/tmp/collection
          rm -rf "$dest_path"
          python3 ./release_collection.py --debug --dest-path "$dest_path"
          # We are up to date - exit
          if git diff --quiet; then
            echo ::info No roles have new releases - no collection will be published
            exit 0
          fi
          # A new collection has been build - find the tarball
          _tarballs=( $(find "$dest_path" -maxdepth 1 -type f -name "*.tar.gz") )
          if [ "${#_tarballs[@]}" -ne 1 ]; then
            echo ::error "Did not find exactly 1 tarball to publish: ${_tarballs[*]}"
            exit 1
          fi
          # Publish the collection
          ansible-galaxy collection publish -vv --token "${{ secrets.GALAXY_API_KEY }}" "${_tarballs[0]}" || echo failed to publish
          # Push the updated collection files. This step should
          # be last since the previous steps must succeed
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -a -m "Collection version was updated"
          git push
          echo ::info Done

      - name: Reenable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()  # Force to always run this step to ensure "include administrators" is always turned back on
        with:
          access_token: ${{ secrets.GH_PUSH_TOKEN }}
          branch: ${{ github.event.repository.default_branch }}
