name: tox
on:  # yamllint disable-line rule:truthy
  - pull_request
  - push
jobs:
  python:
    strategy:
      matrix:
        pyver_os:
          - ver: '3.8'
            os: ubuntu-latest
          - ver: '3.9'
            os: ubuntu-latest
          - ver: '3.10'
            os: ubuntu-latest
          - ver: '3.11'
            os: ubuntu-latest
    runs-on: ${{ matrix.pyver_os.os }}
    steps:
      - name: checkout PR
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyver_os.ver }}
      - name: Install platform dependencies, python, tox
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tox tests
        run: |
          set -euxo pipefail
          tox
